# Generated by Django 3.0.4 on 2020-05-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('summary', models.TextField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
