# Generated by Django 3.0.4 on 2020-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField(default='사진에 대한 설명을 적어주세요')),
            ],
        ),
    ]
