# Generated by Django 3.0.4 on 2020-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_picture_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.TextField(default='사진의 이름을 적어주세요'),
        ),
    ]
