# Generated by Django 3.0.4 on 2020-05-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200525_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='photo',
        ),
    ]
