# Generated by Django 3.0.8 on 2020-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titile',
            new_name='title',
        ),
    ]
