# Generated by Django 3.0.4 on 2020-06-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('productName', models.CharField(max_length=127)),
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('sheetsId', models.IntegerField(primary_key=True, serialize=False)),
                ('GoodsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Goods')),
                ('memberId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Members')),
                ('orderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Orders')),
            ],
        ),
    ]
