# Generated by Django 3.0.4 on 2020-06-30 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goods_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='memberId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Members'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productId',
            field=models.IntegerField(),
        ),
    ]
