# Generated by Django 3.0.4 on 2020-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=30)),
                ('cr_name', models.CharField(max_length=30)),
                ('prefer', models.IntegerField()),
                ('live', models.BooleanField()),
                ('subscr', models.IntegerField()),
                ('vi_link1', models.TextField()),
                ('vi_link2', models.TextField()),
                ('vi_link3', models.TextField()),
            ],
        ),
    ]
